services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/init:/docker-entrypoint-initdb.d
    ports:
      - "${POSTGRES_PORT}:5432"
    healthcheck: 
      interval: 10s
      retries: 10
      test: "pg_isready -U \"${POSTGRES_USER}\" -d \"${POSTGRES_DB}\""
      timeout: 2s

  metabase:
    image: metabase/metabase
    container_name: metabase
    restart: always
    environment:
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: ${METABASE_DB_NAME}
      MB_DB_PORT: 5432
      MB_DB_USER: ${POSTGRES_USER}
      MB_DB_PASS: ${POSTGRES_PASSWORD}
      MB_DB_HOST: postgres
    depends_on:
      - postgres

  n8n:
    image: n8nio/n8n
    container_name: n8n
    restart: always
    user: root
    environment:
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
git push --set-upstream origin main      - NODE_ENV=${NODE_ENV:-production}
      - GENERIC_TIMEZONE=${TIMEZONE:-America/Argentina/Buenos_Aires}
      - TZ=${TIMEZONE:-America/Argentina/Buenos_Aires}
      - N8N_BASIC_AUTH_ACTIVE=false
      - N8N_HOST=${N8N_HOST}
      - N8N_PORT=${N8N_PORT}
      - N8N_PROTOCOL=${N8N_PROTOCOL}
      - WEBHOOK_URL=${N8N_WEBHOOK_URL}
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres
      - DB_POSTGRESDB_DATABASE=${N8N_DB_NAME}
      - DB_POSTGRESDB_USER=${POSTGRES_USER}
      - DB_POSTGRESDB_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - ./n8n_data:/home/node/.n8n
      - ./docs:/files


  nocodb:
    image: nocodb/nocodb
    container_name: nocodb
    restart: always
    environment:
      NC_DB: "pg://postgres:5432?u=${POSTGRES_USER}&p=${POSTGRES_PASSWORD}&d=${NOCODB_DB_NAME}"
    volumes:
      - ./nocodb_data:/usr/app/data
    deploy:
      resources:
        limits:
          memory: 1G

  cloudflared:
    image: cloudflare/cloudflared:latest
    container_name: cloudflared
    restart: always
    command: tunnel run --token ${CLOUDFLARED_TOKEN}
    depends_on:
      - n8n
      - metabase
      - nocodb


